from .cat import Cat
from .dog import Dog
from .sheep import Sheep
from .pig import Pig
from .cow import Cow
from .goat import Goat
from .rat import Rat
from .horse import Horse
from .rabbit import Rabbit
from .panda import Panda
from .squirrel import Squirrel
from .elephant import Elephant
from .lion import Lion
from .wolf import Wolf
from .fox import Fox
from .bear import Bear
from .raccoon import Raccoon
from .deer import Deer
from .kangaroo import Kangaroo
from .tiger import Tiger

from .honeybee import HoneyBee
from .reindeer import Reindeer
from .rat_uv import RatUV
from .goldfish import Goldfish
from .damselfish import Damselfish
from .anableps import Anableps
from .anchovy import Anchovy
